### ISSUE TITLE
Todo - sysinternals functions

### ISSUE THREAD

**Issue by Platanisiotis** [Platanisiotis/PowerShell#1]
- [ ] accesschk.exe	
- [ ] accesschk64.exe	
- [ ] AccessEnum.exe	
- [ ] AdExplorer.chm	
- [ ] ADExplorer.exe	
- [ ] ADInsight.chm	
- [ ] ADInsight.exe	
- [ ] adrestore.exe	
- [ ] Autologon.exe	
- [ ] autoruns.chm	
- [ ] Autoruns.exe	
- [ ] Autoruns64.exe	
- [ ] autorunsc.exe	
- [ ] autorunsc64.exe	
- [ ] Bginfo.exe	
- [ ] Cacheset.exe	
- [ ] Clockres.exe	
- [ ] Clockres64.exe	
- [ ] Contig.exe	
- [ ] Contig64.exe	
- [ ] Coreinfo.exe	
- [ ] ctrl2cap.amd.sys	
- [ ] ctrl2cap.exe	
- [ ] ctrl2cap.nt4.sys	
- [ ] ctrl2cap.nt5.sys	
- [ ] dbgview.chm	
- [ ] Dbgview.exe	
- [ ] Desktops.exe	
- [ ] Disk2vhd.chm	
- [ ] disk2vhd.exe	
- [ ] diskext.exe	
- [ ] diskext64.exe	
- [ ] Diskmon.exe	
- [ ] DISKMON.HLP	
- [ ] DiskView.exe	
- [ ] DMON.SYS	
- [ ] du.exe	
- [ ] du64.exe	
- [ ] efsdump.exe	
- [ ] Eula.txt	
- [ ] FindLinks.exe	
- [ ] FindLinks64.exe	
- [ ] handle.exe	
- [ ] handle64.exe	
- [ ] hex2dec.exe	
- [ ] hex2dec64.exe	
- [ ] junction.exe	
- [ ] junction64.exe	
- [ ] ldmdump.exe	
- [ ] Listdlls.exe	
- [ ] Listdlls64.exe	
- [ ] livekd.exe	
- [ ] LoadOrd.exe	
- [ ] LoadOrd64.exe	
- [ ] LoadOrdC.exe	
- [ ] LoadOrdC64.exe	
- [ ] logonsessions.exe	
- [ ] logonsessions64.exe	
- [ ] movefile.exe	
- [ ] movefile64.exe	
- [ ] notmyfault.exe	
- [ ] notmyfault64.exe	
- [ ] notmyfaultc.exe	
- [ ] notmyfaultc64.exe	
- [ ] ntfsinfo.exe	
- [ ] ntfsinfo64.exe	
- [ ] pagedfrg.exe	
- [ ] pagedfrg.hlp	
- [ ] pendmoves.exe	
- [ ] pendmoves64.exe	
- [ ] pipelist.exe	
- [ ] pipelist64.exe	
- [ ] PORTMON.CNT	
- [ ] portmon.exe	
- [ ] PORTMON.HLP	
- [ ] procdump.exe	
- [ ] procdump64.exe	
- [ ] procexp.chm	
- [ ] procexp.exe	
- [ ] procmon.chm	
- [ ] Procmon.exe	
- [ ] PsExec.exe	
- [ ] PsExec64.exe	
- [ ] psfile.exe	
- [ ] psfile64.exe	
- [ ] PsGetsid.exe	
- [ ] PsGetsid64.exe	
- [ ] PsInfo.exe	
- [ ] PsInfo64.exe	
- [ ] pskill.exe	
- [ ] pskill64.exe	
- [ ] pslist.exe	
- [ ] pslist64.exe	
- [ ] PsLoggedon.exe	
- [ ] PsLoggedon64.exe	
- [ ] psloglist.exe	
- [ ] pspasswd.exe	
- [ ] pspasswd64.exe	
- [ ] psping.exe	
- [ ] psping64.exe	
- [ ] PsService.exe	
- [ ] PsService64.exe	
- [ ] psshutdown.exe	
- [ ] pssuspend.exe	
- [ ] pssuspend64.exe	
- [ ] Pstools.chm	
- [ ] psversion.txt	
- [ ] RAMMap.exe	
- [ ] readme.txt	
- [ ] RegDelNull.exe	
- [ ] RegDelNull64.exe	
- [ ] regjump.exe	
- [ ] RootkitRevealer.chm	
- [ ] RootkitRevealer.exe	
- [ ] ru.exe	
- [ ] ru64.exe	
- [ ] sdelete.exe	
- [ ] sdelete64.exe	
- [ ] ShareEnum.exe	
- [ ] ShellRunas.exe	
- [ ] sigcheck.exe	
- [ ] sigcheck64.exe	
- [ ] streams.exe	
- [ ] streams64.exe	
- [ ] strings.exe	
- [ ] strings64.exe	
- [ ] sync.exe	
- [ ] sync64.exe	
- [ ] Sysmon.exe	
- [ ] Sysmon64.exe	
- [ ] Tcpvcon.exe	
- [ ] tcpview.chm	
- [ ] Tcpview.exe	
- [ ] TCPVIEW.HLP	
- [ ] Testlimit.exe	
- [ ] Testlimit64.exe	
- [ ] Vmmap.chm	
- [ ] vmmap.exe	
- [ ] Volumeid.exe	
- [ ] Volumeid64.exe	
- [ ] whois.exe	
- [ ] whois64.exe	
- [ ] Winobj.exe	
- [ ] WINOBJ.HLP	
- [ ] ZoomIt.exe
